server:
  port: 8999
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8777/eureka/
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods:
              - GET
              - OPTIONS
              - POST
              - PUT
              - DELETE
              - PATCH
            allowed-headers: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: company-management-core
          uri: lb://COMPANY-MANAGEMENT
          predicates:
            - Path=/company-management/**
          filters:
            - RewritePath=/company-management/(?<segment>.*), /$\{segment}
        - id: access-management
          uri: lb://ACCESS-MANAGEMENT
          predicates:
            - Path=/access-management/**
          filters:
            - RewritePath=/access-management/(?<segment>.*), /$\{segment}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/am-realm
logging:
  level:
    root: TRACE
    org:
      springframework:
        cloud:
          gateway: TRACE
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway